services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8888:8888"  # Expose FastAPI port
    networks:
      - app-network
    command: uvicorn api:app --host 0.0.0.0 --port 8888 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm start
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
